spring:
  application:
    name: drug-store-management

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/drug_store_management?createDatabaseIfNotExist=true
    username: root
    password: Vijay@09

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ssnhealthcare1@gmail.com
    password: oalykyfuphdsrodb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000
